# https://taskfile.dev

version: '3'

vars:
  CODE_VERSION: 1.61.1
  FD_VERSION: 8.2.1
  RIPGREP_VERSION: 13.0.0

tasks:
  provision:
    deps:
      - config-git
      - install-apt
      - install-code
      - install-fd
      - install-ripgrep

  config-git:
    cmds:
      - git config --global pull.ff only
      - git config --global user.email takeoverjp@gmail.com
      - git config --global user.name "Kondo Takeo"
    status:
      - git config --get pull.ff
      - git config --get user.email
      - git config --get user.name

  install-apt:
    cmds:
      - sudo add-apt-repository -y ppa:git-core/ppa
      - flock dpkg.lock -c "sudo apt-get update -yqq"
      - flock dpkg.lock -c "sudo apt-get install -y
          build-essential
          ca-certificates
          ctop
          curl
          global
          git
          htop
          tmux
          xsel"

  install-code:
    cmds:
      - "curl -L https://update.code.visualstudio.com/{{.CODE_VERSION}}/linux-deb-x64/stable -o code_{{.CODE_VERSION}}_amd64.deb"
      - flock dpkg.lock -c "sudo dpkg -i code_{{.CODE_VERSION}}_amd64.deb"
      - rm -f code_{{.CODE_VERSION}}_amd64.deb
    status:
      - which code
      - code --version | grep "{{.CODE_VERSION}}"

  install-fd:
    cmds:
      - "curl -LO https://github.com/sharkdp/fd/releases/download/v{{.FD_VERSION}}/fd_{{.FD_VERSION}}_amd64.deb"
      - flock dpkg.lock -c "sudo dpkg -i fd_{{.FD_VERSION}}_amd64.deb"
      - rm -f fd_{{.FD_VERSION}}_amd64.deb
    status:
      - which fd
      - fd --version | grep "{{.FD_VERSION}}"

  install-ripgrep:
    cmds:
      - "curl -LO https://github.com/BurntSushi/ripgrep/releases/download/{{.RIPGREP_VERSION}}/ripgrep_{{.RIPGREP_VERSION}}_amd64.deb"
      - flock dpkg.lock -c "sudo dpkg -i ripgrep_{{.RIPGREP_VERSION}}_amd64.deb"
      - rm -f ripgrep_{{.RIPGREP_VERSION}}_amd64.deb
    status:
      - which rg
      - rg --version | grep "{{.RIPGREP_VERSION}}"
